BEGIN;

CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.schema_migrations (
    version VARCHAR(100) PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'unit')),
    unit_name VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL
);

-- Local password authentication is temporary and separate from the user profile.
-- A future VNeID integration can add an identity without changing qd5277 tables.
CREATE TABLE IF NOT EXISTS app.user_credentials (
    user_id INTEGER PRIMARY KEY REFERENCES app.users(id),
    password_hash TEXT NOT NULL,
    password_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app.user_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES app.users(id),
    provider VARCHAR(50) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    verified_at TIMESTAMPTZ,
    provider_metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    UNIQUE (provider, subject),
    UNIQUE (user_id, provider)
);

CREATE TABLE IF NOT EXISTS app.records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date DATE NOT NULL,
    reporting_mode VARCHAR(20) NOT NULL DEFAULT 'cumulative'
        CHECK (reporting_mode IN ('cumulative', 'incremental')),
    unit_name VARCHAR(255) NOT NULL,
    ma_don_vi_hanh_chinh VARCHAR(10)
        REFERENCES qd5277.DM_DonViHanhChinh(Ma_DonViHanhChinh),
    created_by INTEGER NOT NULL REFERENCES app.users(id),
    area_land NUMERIC(12,2) NOT NULL DEFAULT 0,
    area_tarp NUMERIC(12,2) NOT NULL DEFAULT 0,
    harvest_land NUMERIC(12,2) NOT NULL DEFAULT 0,
    harvest_tarp NUMERIC(12,2) NOT NULL DEFAULT 0,
    sold_land NUMERIC(12,2) NOT NULL DEFAULT 0,
    sold_tarp NUMERIC(12,2) NOT NULL DEFAULT 0,
    remaining_land NUMERIC(12,2) NOT NULL DEFAULT 0,
    remaining_tarp NUMERIC(12,2) NOT NULL DEFAULT 0,
    processed_fine NUMERIC(12,2) NOT NULL DEFAULT 0,
    processed_iodized NUMERIC(12,2) NOT NULL DEFAULT 0,
    households INTEGER NOT NULL DEFAULT 0,
    workers INTEGER NOT NULL DEFAULT 0,
    price_land TEXT NOT NULL DEFAULT '',
    price_tarp TEXT NOT NULL DEFAULT '',
    damage_land NUMERIC(12,2) NOT NULL DEFAULT 0,
    damage_tarp NUMERIC(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'submitted', 'approved', 'returned')),
    note TEXT NOT NULL DEFAULT '',
    reviewer_note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    submitted_at TEXT,
    approved_at TEXT,
    UNIQUE (unit_name, report_date)
);

CREATE TABLE IF NOT EXISTS app.audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id INTEGER REFERENCES app.records(id),
    user_id INTEGER REFERENCES app.users(id),
    action TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    module TEXT,
    object_type TEXT,
    object_id TEXT
);

CREATE TABLE IF NOT EXISTS app.user_admin_units (
    user_id INTEGER PRIMARY KEY REFERENCES app.users(id),
    ma_don_vi_hanh_chinh VARCHAR(10) NOT NULL
        REFERENCES qd5277.DM_DonViHanhChinh(Ma_DonViHanhChinh)
);

-- OCOP workflow is initialized only. No official OCOP data is seeded or normalized.
CREATE TABLE IF NOT EXISTS app.ocop_entities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_co_so VARCHAR(10) NOT NULL UNIQUE REFERENCES qd5277.DM_CoSo(Ma_CoSo),
    representative_name TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    tax_code TEXT NOT NULL DEFAULT '',
    website TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    created_by INTEGER NOT NULL REFERENCES app.users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT
);

CREATE TABLE IF NOT EXISTS app.ocop_products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_san_pham VARCHAR(10) NOT NULL REFERENCES qd5277.DM_SanPham(Ma_SanPham),
    ma_co_so VARCHAR(10) NOT NULL REFERENCES qd5277.DM_CoSo(Ma_CoSo),
    ma_don_vi_hanh_chinh VARCHAR(10) NOT NULL
        REFERENCES qd5277.DM_DonViHanhChinh(Ma_DonViHanhChinh),
    ten_san_pham VARCHAR(255) NOT NULL,
    product_group VARCHAR(100) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    current_star INTEGER CHECK (current_star IS NULL OR current_star IN (3,4,5)),
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'archived')),
    created_by INTEGER NOT NULL REFERENCES app.users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app.ocop_applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES app.ocop_products(id),
    evaluation_type VARCHAR(30) NOT NULL
        CHECK (evaluation_type IN ('new', 're_evaluation', 'upgrade')),
    year INTEGER NOT NULL CHECK (year BETWEEN 1900 AND 9999),
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'submitted', 'checking', 'returned',
                          'eligible', 'scoring', 'completed', 'cancelled')),
    submitted_at TEXT,
    checked_at TEXT,
    reviewer_id INTEGER REFERENCES app.users(id),
    reviewer_note TEXT NOT NULL DEFAULT '',
    created_by INTEGER NOT NULL REFERENCES app.users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),
    submission_snapshot_json TEXT
);

CREATE TABLE IF NOT EXISTS app.ocop_reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INTEGER NOT NULL REFERENCES app.ocop_applications(id),
    reviewer_id INTEGER NOT NULL REFERENCES app.users(id),
    action TEXT NOT NULL,
    comment TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS IX_App_RecordFilter
    ON app.records(status, report_date, unit_name, id);
CREATE INDEX IF NOT EXISTS IX_App_RecordAdminPeriod
    ON app.records(ma_don_vi_hanh_chinh, report_date, status);
CREATE INDEX IF NOT EXISTS IX_App_AuditRecord
    ON app.audit_logs(record_id, id);
CREATE INDEX IF NOT EXISTS IX_App_AuditModule
    ON app.audit_logs(module, object_type, object_id, id);
CREATE INDEX IF NOT EXISTS IX_App_OCOPProductUnit
    ON app.ocop_products(ma_don_vi_hanh_chinh, status, id);
CREATE INDEX IF NOT EXISTS IX_App_OCOPApplicationStatus
    ON app.ocop_applications(status, year, id);

-- Technical uniqueness for deterministic monthly UPSERT; no QD 5277 field is added.
CREATE UNIQUE INDEX IF NOT EXISTS UX_DN_SanLuongMuoi_Monthly
    ON qd5277.DN_SanLuongMuoi
       (Ma_DonViHanhChinh, Ma_ThoiGian, PhuongPhapSX);

INSERT INTO app.schema_migrations(version)
VALUES ('app_001_foundation')
ON CONFLICT (version) DO NOTHING;

COMMIT;
