BEGIN;

CREATE TABLE IF NOT EXISTS app.ocop_criteria_sets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    product_category VARCHAR(150) NOT NULL,
    product_group VARCHAR(150) NOT NULL,
    product_subgroup VARCHAR(255) NOT NULL DEFAULT '',
    legal_document VARCHAR(100) NOT NULL,
    version VARCHAR(50) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    max_score NUMERIC NOT NULL DEFAULT 100 CHECK (max_score > 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL CHECK (sort_order > 0),
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app.ocop_criteria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criteria_set_id INTEGER NOT NULL REFERENCES app.ocop_criteria_sets(id),
    parent_id INTEGER REFERENCES app.ocop_criteria(id),
    code VARCHAR(50) NOT NULL,
    title VARCHAR(500) NOT NULL,
    item_type VARCHAR(20) NOT NULL
        CHECK (item_type IN ('section', 'group', 'criterion', 'note')),
    section_code VARCHAR(1) CHECK (section_code IS NULL OR section_code IN ('A', 'B', 'C')),
    max_score NUMERIC CHECK (max_score IS NULL OR max_score >= 0),
    requirement_text TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (criteria_set_id, code)
);

CREATE TABLE IF NOT EXISTS app.ocop_criteria_options (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterion_id INTEGER NOT NULL REFERENCES app.ocop_criteria(id),
    label VARCHAR(2000) NOT NULL,
    score NUMERIC NOT NULL CHECK (score >= 0),
    min_star INTEGER CHECK (min_star IS NULL OR min_star IN (3, 4, 5)),
    is_eliminating BOOLEAN NOT NULL DEFAULT FALSE,
    evidence_hint TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE app.ocop_products
    ADD COLUMN IF NOT EXISTS criteria_set_id INTEGER REFERENCES app.ocop_criteria_sets(id);
ALTER TABLE app.ocop_applications
    ADD COLUMN IF NOT EXISTS criteria_set_id INTEGER REFERENCES app.ocop_criteria_sets(id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_OCOP_CriteriaSetSort
    ON app.ocop_criteria_sets(sort_order);
CREATE INDEX IF NOT EXISTS IX_OCOP_CriteriaSetActive
    ON app.ocop_criteria_sets(active, sort_order);
CREATE INDEX IF NOT EXISTS IX_OCOP_CriteriaSetClass
    ON app.ocop_criteria_sets(product_category, product_group, active);
CREATE INDEX IF NOT EXISTS IX_OCOP_CriteriaTree
    ON app.ocop_criteria(criteria_set_id, parent_id, sort_order, id);
CREATE INDEX IF NOT EXISTS IX_OCOP_CriteriaOptions
    ON app.ocop_criteria_options(criterion_id, sort_order, id);
CREATE INDEX IF NOT EXISTS IX_OCOP_ProductCriteriaSet
    ON app.ocop_products(criteria_set_id, status, id);
CREATE INDEX IF NOT EXISTS IX_OCOP_ApplicationCriteriaSet
    ON app.ocop_applications(criteria_set_id, status, id);

INSERT INTO app.ocop_criteria_sets
    (code, name, product_category, product_group, product_subgroup,
     legal_document, version, effective_from, effective_to, max_score,
     active, sort_order, notes, created_at, updated_at)
VALUES
    ('QD26-01', 'Rau, củ, quả, hạt tươi', 'Thực phẩm', 'Thực phẩm tươi sống', 'Rau, củ, quả, hạt tươi', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 1, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-02', 'Thịt, thủy sản, trứng, sữa tươi', 'Thực phẩm', 'Thực phẩm tươi sống', 'Thịt, thủy sản, trứng, sữa tươi', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 2, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-03', 'Gạo, ngũ cốc, hạt sơ chế khác', 'Thực phẩm', 'Thực phẩm thô, sơ chế', 'Gạo, ngũ cốc, hạt sơ chế khác', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 3, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-04', 'Mật ong, mật khác và nông sản thực phẩm khác', 'Thực phẩm', 'Thực phẩm thô, sơ chế', 'Mật ong, mật khác và nông sản thực phẩm khác', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 4, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-05', 'Đồ ăn nhanh', 'Thực phẩm', 'Thực phẩm chế biến', 'Đồ ăn nhanh', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 5, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-06', 'Chế biến từ gạo, ngũ cốc', 'Thực phẩm', 'Thực phẩm chế biến', 'Chế biến từ gạo, ngũ cốc', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 6, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-07', 'Chế biến từ rau, củ, quả, hạt', 'Thực phẩm', 'Thực phẩm chế biến', 'Chế biến từ rau, củ, quả, hạt', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 7, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-08', 'Chế biến từ thịt, thủy sản, trứng, sữa, các sản phẩm từ mật ong, mật khác và nông sản thực phẩm khác', 'Thực phẩm', 'Thực phẩm chế biến', 'Chế biến từ thịt, trứng, sữa, thủy sản và nông sản thực phẩm khác', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 8, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-09', 'Tương, nước mắm, gia vị dạng lỏng khác', 'Thực phẩm', 'Gia vị', 'Tương, nước mắm, gia vị dạng lỏng khác', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 9, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-10', 'Gia vị khác (muối, hành, tỏi, tiêu)', 'Thực phẩm', 'Gia vị', 'Gia vị khác', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 10, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-11', 'Chè tươi, chè chế biến', 'Thực phẩm', 'Chè', 'Chè tươi, chế biến', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 11, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-12', 'Sản phẩm trà từ thực vật khác', 'Thực phẩm', 'Chè', 'Sản phẩm chè từ thực vật khác', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 12, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-13', 'Cà phê, cacao', 'Thực phẩm', 'Cà phê, ca cao', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 13, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-14', 'Rượu trắng', 'Đồ uống', 'Đồ uống có cồn', 'Rượu trắng', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 14, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-15', 'Đồ uống có cồn khác', 'Đồ uống', 'Đồ uống có cồn', 'Đồ uống có cồn khác', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 15, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-16', 'Nước khoáng thiên nhiên, nước uống đóng chai', 'Đồ uống', 'Đồ uống không cồn', 'Nước khoáng thiên nhiên, nước uống đóng chai', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 16, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-17', 'Đồ uống không cồn khác', 'Đồ uống', 'Đồ uống không cồn', 'Đồ uống không cồn', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 17, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-18', 'Thực phẩm chức năng, thuốc dược liệu, thuốc cổ truyền', 'Dược liệu và sản phẩm từ dược liệu', 'Thực phẩm chức năng, thuốc dược liệu, thuốc cổ truyền', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 18, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-19', 'Mỹ phẩm có thành phần từ dược liệu', 'Dược liệu và sản phẩm từ dược liệu', 'Mỹ phẩm có thành phần từ dược liệu', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 19, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-20', 'Tinh dầu và dược liệu khác', 'Dược liệu và sản phẩm từ dược liệu', 'Tinh dầu và dược liệu khác', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 20, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-21', 'Thủ công mỹ nghệ', 'Hàng thủ công mỹ nghệ', 'Thủ công mỹ nghệ gia dụng, trang trí', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 21, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-22', 'Vải, may mặc', 'Hàng thủ công mỹ nghệ', 'Vải, may mặc', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 22, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-23', 'Hoa', 'Sinh vật cảnh', 'Hoa', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 23, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-24', 'Cây cảnh', 'Sinh vật cảnh', 'Cây cảnh', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 24, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-25', 'Động vật cảnh', 'Sinh vật cảnh', 'Động vật cảnh', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 25, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00'),
    ('QD26-26', 'Dịch vụ du lịch cộng đồng, du lịch sinh thái và điểm du lịch', 'Dịch vụ du lịch cộng đồng, du lịch sinh thái và điểm du lịch', 'Dịch vụ du lịch cộng đồng, du lịch sinh thái và điểm du lịch', '', '26/2026/QĐ-TTg', '2026.1', DATE '2026-05-22', NULL, 100, TRUE, 26, 'Khung bộ tiêu chí theo Phụ lục II; tiêu chí chi tiết được quản lý dạng dữ liệu động.', '2026-05-22 00:00:00', '2026-05-22 00:00:00')
ON CONFLICT (code) DO NOTHING;

INSERT INTO app.ocop_criteria
    (criteria_set_id, parent_id, code, title, item_type, section_code,
     max_score, requirement_text, sort_order, active)
SELECT sets.id, NULL, sections.code, sections.title, 'section', sections.code,
       sections.max_score, '', sections.sort_order, TRUE
FROM app.ocop_criteria_sets AS sets
CROSS JOIN (VALUES
    ('A', 'Sản phẩm và sức mạnh của cộng đồng', 40, 10),
    ('B', 'Khả năng tiếp thị', 25, 20),
    ('C', 'Chất lượng sản phẩm', 35, 30)
) AS sections(code, title, max_score, sort_order)
WHERE sets.code LIKE 'QD26-%'
ON CONFLICT (criteria_set_id, code) DO NOTHING;

DO $$
DECLARE
    invalid_sets INTEGER;
    invalid_sections INTEGER;
BEGIN
    SELECT count(*) INTO invalid_sets
    FROM app.ocop_criteria_sets
    WHERE code LIKE 'QD26-%'
      AND (legal_document <> '26/2026/QĐ-TTg' OR version <> '2026.1'
           OR effective_from <> DATE '2026-05-22' OR max_score <> 100 OR NOT active);

    SELECT count(*) INTO invalid_sections
    FROM app.ocop_criteria AS criteria
    JOIN app.ocop_criteria_sets AS sets ON sets.id = criteria.criteria_set_id
    WHERE sets.code LIKE 'QD26-%' AND criteria.code IN ('A', 'B', 'C')
      AND (criteria.item_type <> 'section' OR NOT criteria.active);

    IF (SELECT count(*) FROM app.ocop_criteria_sets WHERE code LIKE 'QD26-%') <> 26
       OR invalid_sets <> 0
       OR (SELECT count(*) FROM app.ocop_criteria AS criteria
           JOIN app.ocop_criteria_sets AS sets ON sets.id = criteria.criteria_set_id
           WHERE sets.code LIKE 'QD26-%' AND criteria.code IN ('A', 'B', 'C')) <> 78
       OR invalid_sections <> 0 THEN
        RAISE EXCEPTION 'Danh mục OCOP QD26 hiện có không khớp migration chuẩn.';
    END IF;
END $$;

INSERT INTO app.schema_migrations(version)
VALUES ('app_006_ocop_dynamic_criteria')
ON CONFLICT (version) DO NOTHING;

COMMIT;
