BEGIN;

CREATE TABLE IF NOT EXISTS app.salt_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    file_sha256 CHAR(64) NOT NULL,
    sheet_name TEXT NOT NULL,
    week_code VARCHAR(8) NOT NULL,
    report_date DATE NOT NULL,
    template_version VARCHAR(20) NOT NULL DEFAULT 'weekly-v1',
    import_mode VARCHAR(10) NOT NULL CHECK (import_mode IN ('skip', 'update')),
    total_rows INTEGER NOT NULL CHECK (total_rows >= 0),
    warning_rows INTEGER NOT NULL DEFAULT 0 CHECK (warning_rows >= 0),
    imported_rows INTEGER NOT NULL DEFAULT 0 CHECK (imported_rows >= 0),
    updated_rows INTEGER NOT NULL DEFAULT 0 CHECK (updated_rows >= 0),
    skipped_rows INTEGER NOT NULL DEFAULT 0 CHECK (skipped_rows >= 0),
    imported_by INTEGER NOT NULL REFERENCES app.users(id),
    imported_at TEXT NOT NULL,
    UNIQUE (file_sha256, sheet_name, week_code)
);

CREATE TABLE IF NOT EXISTS staging.salt_weekly_import_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES app.salt_import_batches(id) ON DELETE CASCADE,
    excel_row INTEGER NOT NULL,
    unit_name_raw TEXT NOT NULL,
    ma_don_vi_hanh_chinh VARCHAR(10),
    validation_status VARCHAR(10) NOT NULL CHECK (validation_status IN ('valid', 'warning')),
    validation_messages_json TEXT NOT NULL DEFAULT '[]',
    raw_data_json TEXT NOT NULL,
    canonical_data_json TEXT NOT NULL,
    UNIQUE (batch_id, excel_row)
);

CREATE TABLE IF NOT EXISTS app.salt_weekly_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES app.salt_import_batches(id),
    week_code VARCHAR(8) NOT NULL,
    report_date DATE NOT NULL,
    unit_name VARCHAR(255) NOT NULL,
    ma_don_vi_hanh_chinh VARCHAR(10) NOT NULL
        REFERENCES qd5277.DM_DonViHanhChinh(Ma_DonViHanhChinh),
    phuong_phap_sx VARCHAR(100) NOT NULL DEFAULT 'Truyền thống',
    dien_tich NUMERIC(12,2) NOT NULL CHECK (dien_tich >= 0),
    san_luong NUMERIC(12,2) NOT NULL CHECK (san_luong >= 0),
    gia_ban_binh_quan NUMERIC(12,2) CHECK (gia_ban_binh_quan IS NULL OR gia_ban_binh_quan >= 0),
    area_land NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (area_land >= 0),
    area_tarp NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (area_tarp >= 0),
    harvest_land NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (harvest_land >= 0),
    harvest_tarp NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (harvest_tarp >= 0),
    sold_land NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (sold_land >= 0),
    sold_tarp NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (sold_tarp >= 0),
    remaining_land NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (remaining_land >= 0),
    remaining_tarp NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (remaining_tarp >= 0),
    processed_fine NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (processed_fine >= 0),
    processed_iodized NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (processed_iodized >= 0),
    households INTEGER NOT NULL DEFAULT 0 CHECK (households >= 0),
    workers INTEGER NOT NULL DEFAULT 0 CHECK (workers >= 0),
    price_land TEXT NOT NULL DEFAULT '',
    price_tarp TEXT NOT NULL DEFAULT '',
    damage_land NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (damage_land >= 0),
    damage_tarp NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (damage_tarp >= 0),
    note TEXT NOT NULL DEFAULT '',
    created_by INTEGER NOT NULL REFERENCES app.users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (ma_don_vi_hanh_chinh, week_code)
);

CREATE INDEX IF NOT EXISTS IX_SaltWeeklyRecordPeriod
    ON app.salt_weekly_records(week_code, ma_don_vi_hanh_chinh);
CREATE INDEX IF NOT EXISTS IX_SaltImportBatchPeriod
    ON app.salt_import_batches(week_code, imported_at DESC);

CREATE OR REPLACE VIEW app.v_dn_sanluongmuoi_weekly_qd5277 AS
SELECT id AS Ma_SanLuongMuoi,
       ma_don_vi_hanh_chinh AS Ma_DonViHanhChinh,
       week_code AS Ma_ThoiGian,
       phuong_phap_sx AS PhuongPhapSX,
       dien_tich AS DienTich,
       san_luong AS SanLuong,
       gia_ban_binh_quan AS GiaBanBinhQuan
FROM app.salt_weekly_records;

INSERT INTO app.schema_migrations(version)
VALUES ('app_008_weekly_salt_imports')
ON CONFLICT (version) DO NOTHING;

COMMIT;
