BEGIN;

CREATE TABLE IF NOT EXISTS staging.ocop_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    file_sha256 CHAR(64) NOT NULL,
    sheet_name VARCHAR(255) NOT NULL,
    total_rows INTEGER NOT NULL DEFAULT 0 CHECK (total_rows >= 0),
    valid_rows INTEGER NOT NULL DEFAULT 0 CHECK (valid_rows >= 0),
    warning_rows INTEGER NOT NULL DEFAULT 0 CHECK (warning_rows >= 0),
    error_rows INTEGER NOT NULL DEFAULT 0 CHECK (error_rows >= 0),
    commit_mode VARCHAR(20) NOT NULL CHECK (commit_mode IN ('stage_only', 'publish')),
    status VARCHAR(20) NOT NULL DEFAULT 'committed' CHECK (status IN ('committed', 'published')),
    imported_by INTEGER NOT NULL REFERENCES app.users(id),
    imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    UNIQUE (file_sha256, sheet_name)
);

CREATE TABLE IF NOT EXISTS staging.ocop_import_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES staging.ocop_import_batches(id) ON DELETE CASCADE,
    excel_row INTEGER NOT NULL CHECK (excel_row > 0),
    source_tt VARCHAR(50),
    source_unit_name VARCHAR(255),
    mapped_unit_code VARCHAR(10) REFERENCES qd5277.DM_DonViHanhChinh(Ma_DonViHanhChinh),
    validation_status VARCHAR(10) NOT NULL CHECK (validation_status IN ('valid', 'warning', 'error')),
    validation_messages_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    raw_data_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    canonical_data_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, excel_row)
);

ALTER TABLE app.ocop_entities
    ADD COLUMN IF NOT EXISTS source_key VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS UX_OCOP_EntitySourceKey
    ON app.ocop_entities(source_key)
    WHERE source_key IS NOT NULL;

ALTER TABLE app.ocop_products
    ADD COLUMN IF NOT EXISTS source_key VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS UX_OCOP_ProductSourceKey
    ON app.ocop_products(source_key)
    WHERE source_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS app.ocop_recognitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES app.ocop_products(id),
    application_id INTEGER REFERENCES app.ocop_applications(id),
    source_key VARCHAR(64) NOT NULL UNIQUE,
    recognition_sequence INTEGER NOT NULL CHECK (recognition_sequence >= 1),
    evaluation_type VARCHAR(30) NOT NULL
        CHECK (evaluation_type IN ('new', 're_evaluation', 'upgrade', 'historical')),
    star_rank INTEGER NOT NULL CHECK (star_rank IN (3, 4, 5)),
    recognition_date DATE,
    recognition_year INTEGER NOT NULL CHECK (recognition_year BETWEEN 1900 AND 9999),
    decision_number VARCHAR(100) NOT NULL DEFAULT '',
    decision_authority VARCHAR(255) NOT NULL DEFAULT '',
    expiry_date DATE,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    note TEXT NOT NULL DEFAULT '',
    source_batch_id BIGINT REFERENCES staging.ocop_import_batches(id),
    source_row INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (product_id, recognition_sequence)
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_OCOP_RecognitionCurrent
    ON app.ocop_recognitions(product_id)
    WHERE is_current = TRUE;
CREATE INDEX IF NOT EXISTS IX_OCOP_RecognitionProduct
    ON app.ocop_recognitions(product_id, recognition_year DESC, recognition_sequence DESC);
CREATE INDEX IF NOT EXISTS IX_OCOP_RecognitionBatch
    ON app.ocop_recognitions(source_batch_id, source_row);
CREATE INDEX IF NOT EXISTS IX_OCOP_ImportRowBatch
    ON staging.ocop_import_rows(batch_id, validation_status, excel_row);

INSERT INTO app.schema_migrations(version)
VALUES ('app_011_ocop_legacy_import')
ON CONFLICT (version) DO NOTHING;

COMMIT;
