BEGIN;

CREATE TABLE IF NOT EXISTS app.ocop_recognitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES app.ocop_products(id) ON DELETE CASCADE,
    recognition_round INTEGER NOT NULL CHECK (recognition_round >= 1),
    star INTEGER CHECK (star IS NULL OR star BETWEEN 1 AND 5),
    recognized_on DATE,
    decision_number VARCHAR(100),
    issuing_authority VARCHAR(255),
    expires_on DATE,
    UNIQUE (product_id, recognition_round)
);

CREATE TABLE IF NOT EXISTS app.ocop_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    file_sha256 CHAR(64) NOT NULL,
    sheet_name VARCHAR(255) NOT NULL,
    total_rows INTEGER NOT NULL DEFAULT 0,
    imported_rows INTEGER NOT NULL DEFAULT 0,
    updated_rows INTEGER NOT NULL DEFAULT 0,
    skipped_rows INTEGER NOT NULL DEFAULT 0,
    error_rows INTEGER NOT NULL DEFAULT 0,
    imported_by INTEGER REFERENCES app.users(id),
    imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (file_sha256, sheet_name)
);

CREATE TABLE IF NOT EXISTS app.ocop_import_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES app.ocop_import_batches(id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL,
    field_name VARCHAR(100),
    raw_value TEXT,
    error_message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app.admin_unit_code_mapping (
    temp_code VARCHAR(10) PRIMARY KEY,
    source_name VARCHAR(255) NOT NULL UNIQUE,
    official_code VARCHAR(10),
    mapped_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_App_OCOPProductEntityName
    ON app.ocop_products (ma_co_so, lower(ten_san_pham));
CREATE UNIQUE INDEX IF NOT EXISTS UX_QD5277_PTNTOCOP_ProductTime
    ON qd5277.PTNT_OCOP (Ma_SanPham, Ma_ThoiGian);
CREATE INDEX IF NOT EXISTS IX_App_OCOPRecognitionProduct
    ON app.ocop_recognitions(product_id, recognition_round);
CREATE INDEX IF NOT EXISTS IX_App_OCOPImportBatchTime
    ON app.ocop_import_batches(imported_at DESC);
CREATE INDEX IF NOT EXISTS IX_App_AdminUnitMappingSource
    ON app.admin_unit_code_mapping(lower(source_name));

INSERT INTO app.schema_migrations(version)
VALUES ('app_011_ocop_excel_import')
ON CONFLICT (version) DO NOTHING;

COMMIT;
