BEGIN;

CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS staging;

-- The running OCOP importer historically uses an unqualified
-- ocop_import_batches name.  Expose a writable compatibility view in app;
-- its rows remain physically stored in staging, the existing source of truth.
CREATE OR REPLACE VIEW app.ocop_import_batches AS
SELECT id, filename, file_sha256, sheet_name, total_rows, valid_rows,
       warning_rows, error_rows, commit_mode, status, imported_by, imported_at,
       published_at
FROM staging.ocop_import_batches;

CREATE TABLE IF NOT EXISTS app.code_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_type VARCHAR(50) NOT NULL,
    source_system VARCHAR(100) NOT NULL,
    source_code VARCHAR(255) NOT NULL,
    source_label VARCHAR(255) NOT NULL DEFAULT '',
    canonical_schema VARCHAR(63) NOT NULL,
    canonical_table VARCHAR(63) NOT NULL,
    canonical_code VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    note VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (mapping_type, source_system, source_code)
);

COMMENT ON VIEW app.ocop_import_batches IS
    'Compatibility alias; physical rows are in staging.ocop_import_batches.';
COMMENT ON TABLE app.code_mappings IS
    'Temporary-to-canonical mapping layer; never replaces QD 5277/QD 5333 keys.';

INSERT INTO app.schema_migrations(version)
VALUES ('app_012_production_runtime')
ON CONFLICT (version) DO NOTHING;

COMMIT;
